<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>eShop.Identity.API</RootNamespace>
    <UserSecretsId>aspnet-eShop.Identity.API-e3f3fc80-b16d-4466-a745-de896c9ae3a4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityServer.AspNetIdentity" />
    <PackageReference Include="Duende.IdentityServer.Storage" />
    <PackageReference Include="Duende.IdentityServer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\MigrateDbContextExtensions.cs" Link="Extensions\MigrateDbContextExtensions.cs" />
    <Compile Include="..\Shared\Abstractions\IDbSeeder.cs" Link="Abstractions\IDbSeeder.cs" />
    <Compile Include="..\Shared\ActivityExtensions.cs" Link="Extensions\ActivityExtensions.cs" />
  </ItemGroup>

</Project>
